apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  label:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default